# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

application_url = "https://tournaments-donate-kinase-visited.trycloudflare.com"
client_id = "f87f40305e8735770ffe121daf5a9b51"
embedded = true
name = "Tokengating-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_gates,write_gates,read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://tournaments-donate-kinase-visited.trycloudflare.com/auth/callback",
  "https://tournaments-donate-kinase-visited.trycloudflare.com/auth/shopify/callback",
  "https://tournaments-donate-kinase-visited.trycloudflare.com/api/auth/callback",
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "skylaketeststore.myshopify.com"
